### ISSUE TITLE
Why multiple  "belongs_to :accountable" polymorphic association?

### ISSUE THREAD

**Issue by hainam8x** [ledermann/keepr#13]
Hi @ledermann , could you help me to understand why there are multiple polymorphic association "belongs_to :accountable" in Account, Journal and Posting model? 
Is this an error or have a real life use case?

**Comment by ledermann** [comment]
This is not an error. The `accountable` association allows linking to an external object. Here are the use cases:

- `Account`: If you have a `Contact` model, you can define an account for each contact. This is useful for handling debtors and creditors (see enum `Account#kind`)
- `Journal`: If you have models for debts or invoices, you can link them to `journals`. Useful to see if an invoice is already booked or not.
- `Posting`: Linking a `Posting` to an invoice helps to close it. Think of an invoice which is fully paid by two payments: There will be two `journals` (one for each payment, linked by `journal.accountable`). Each `journal` has two `postings`, one of them is linked to the invoice by `posting.accountable`. Calculating the sum of `postings.amount` for a given invoice allows you to see the balance of the invoice.

Of course, all of these associations are optional. But it allows integrating book keeping stuff to you application models.

**Comment by hainam8x** [comment]
Thanks, it clear now
