### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nhorob67** [ledermann/keepr#2]
Looking for a double entry rails gem and see that you have sub-accounts and cost centers (two high priority wants!).  Would love to see expanded documentation.  Thanks for your work on this so far.

**Comment by azeemh** [comment]
yes please how does one use this?

**Comment by fameoflight** [comment]
@azeemh @nhorob67 what did you guys end up using?

@ledermann any chance we can get the documentation?

**Comment by jaydorsey** [comment]
[double_entry](https://github.com/envato/double_entry) has the best documentation I've seen yet of the double entry accounting gems

**Comment by ledermann** [comment]
Sorry folks, the gem is used heavily in one of my applications and it works fine for years, but currently there is no time to work on this project. So writing the docs for will stay on my todo list even longer.

**Comment by martinGerez** [comment]
Hey, I will try to add some new features that are in my mind and improve the documentations through my personal use of this gem :)

**Comment by martinGerez** [comment]
@ledermann I'm thinking about the best way to document the gem.
In order to cover all concepts, I plan to write first the concepts from a general point of view, like Accounts, Journals, Postings, etc.
And after that, write some use cases.

Have you another idea about this? Thanks!

**Comment by ledermann** [comment]
@martinGerez Great! Since I'm busy with other projects, I have no further ideas for documentation. Just one thing: Do you think the wiki is a good place for documentation? I tend to prefer that.

Anyway, I'm curious what you're going to do, and I'll be happy to look at the docs.
