### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by miguelperez** [ledermann/keepr#8]
Hi, I am open to helping to work on this.
I would like to know if there is a roadmap for the development of features of this product.

Are you open to contributions?

**Comment by ledermann** [comment]
This project is used in production in some of my applications. For my use cases it is feature complete.

It would be nice to get some improvements, but currently my time for working on this is **very** limited. Nevertheless, contributions are welcome.

**Comment by miguelperez** [comment]
Hi, thanks for your reply. 
Where can I see a list of improvements?

**Comment by ledermann** [comment]
Currently, there's no such list. IMHO, the lack of documentation is the biggest issue.
